// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DaiPhatDat.Core.Kernel.Notifications.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialNotification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialNotification));

        string IMigrationMetadata.Id
        {
            get { return "202008241428131_InitialNotification"; }
        }

        string IMigrationMetadata.Source
        {
            get { return null; }
        }

        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
